### ISSUE TITLE
Standalone IndexMap to Lua table library

### ISSUE THREAD

**Issue by Bobrokus** [DervexDev/toml2lua#1]
I need to convert an Rust data into Lua, but I don't need the Toml part of this library, so it would be helpful to have a separate library.

**Comment by DervexDev** [comment]
This feature does not fit this crate as it's intended for converting TOML files only. Another thing is that this crate relies on `toml::Value` when serializing and `IndexMap` can contain any other struct and thus it would require a completely different implementation.

I recommend looking for another crate or as a workaround serialize your `IndexMap` into a TOML string and then serialize it into Lua but this isn't an optimal solution to say the least.

**Comment by Bobrokus** [comment]
> This feature does not fit this crate as it's intended for converting TOML files only. Another thing is that this crate relies on `toml::Value` when serializing and `IndexMap` can contain any other struct and thus it would require a completely different implementation.
> 
> I recommend looking for another crate or as a workaround serialize your `IndexMap` into a TOML string and then serialize it into Lua but this isn't an optimal solution to say the least.

Hi! Thanks for the reply. What I meant was to create a new crate specifically for turning Rust to Lua. That doesn't matter though. I'm currently working on my implementation of this idea.
